export CUDA_VISIBLE_DEVICES="3"


python main_knn.py --config-path ./configs/knn4/ --config-name default_empssl6_0.yaml 
python main_knn.py --config-path ./configs/knn4/ --config-name default_empssl6_1.yaml 
python main_knn.py --config-path ./configs/knn4/ --config-name default_empssl6_2.yaml 
python main_knn.py --config-path ./configs/knn4/ --config-name default_empssl6_3.yaml 
python main_knn.py --config-path ./configs/knn4/ --config-name default_empssl6_4.yaml 
python main_knn.py --config-path ./configs/knn4/ --config-name default_empssl6_5.yaml 
python main_knn.py --config-path ./configs/knn4/ --config-name default_empssl6_6.yaml 
python main_knn.py --config-path ./configs/knn4/ --config-name default_empssl6_7.yaml 
python main_knn.py --config-path ./configs/knn4/ --config-name default_empssl6_8.yaml 
python main_knn.py --config-path ./configs/knn4/ --config-name default_empssl6_9.yaml 
python main_knn.py --config-path ./configs/knn4/ --config-name default_empssl6_10.yaml 
python main_knn.py --config-path ./configs/knn4/ --config-name default_empssl6_11.yaml 
python main_knn.py --config-path ./configs/knn4/ --config-name default_empssl6_12.yaml 
python main_knn.py --config-path ./configs/knn4/ --config-name default_empssl6_13.yaml 
python main_knn.py --config-path ./configs/knn4/ --config-name default_empssl6_14.yaml 
python main_knn.py --config-path ./configs/knn4/ --config-name default_empssl6_15.yaml 
python main_knn.py --config-path ./configs/knn4/ --config-name default_empssl6_16.yaml 
python main_knn.py --config-path ./configs/knn4/ --config-name default_empssl6_17.yaml 
python main_knn.py --config-path ./configs/knn4/ --config-name default_empssl6_18.yaml 
python main_knn.py --config-path ./configs/knn4/ --config-name default_empssl6_19.yaml 
python main_knn.py --config-path ./configs/knn4/ --config-name default_empssl6_20.yaml 
python main_knn.py --config-path ./configs/knn4/ --config-name default_empssl6_21.yaml 
python main_knn.py --config-path ./configs/knn4/ --config-name default_empssl6_22.yaml 
python main_knn.py --config-path ./configs/knn4/ --config-name default_empssl6_23.yaml 
python main_knn.py --config-path ./configs/knn4/ --config-name default_empssl6_24.yaml 
python main_knn.py --config-path ./configs/knn4/ --config-name default_empssl6_25.yaml 
python main_knn.py --config-path ./configs/knn4/ --config-name default_empssl6_26.yaml 
python main_knn.py --config-path ./configs/knn4/ --config-name default_empssl6_27.yaml 
python main_knn.py --config-path ./configs/knn4/ --config-name default_empssl6_28.yaml 
python main_knn.py --config-path ./configs/knn4/ --config-name default_empssl6_29.yaml 
python main_knn.py --config-path ./configs/knn4/ --config-name default_empssl6_30.yaml 
python main_knn.py --config-path ./configs/knn4/ --config-name default_empssl6_31.yaml 
python main_knn.py --config-path ./configs/knn4/ --config-name default_empssl6_32.yaml 
python main_knn.py --config-path ./configs/knn4/ --config-name default_empssl6_33.yaml 
python main_knn.py --config-path ./configs/knn4/ --config-name default_empssl6_34.yaml 
python main_knn.py --config-path ./configs/knn4/ --config-name default_empssl6_35.yaml 
python main_knn.py --config-path ./configs/knn4/ --config-name default_empssl6_36.yaml 
python main_knn.py --config-path ./configs/knn4/ --config-name default_empssl6_37.yaml 
python main_knn.py --config-path ./configs/knn4/ --config-name default_empssl6_38.yaml 
python main_knn.py --config-path ./configs/knn4/ --config-name default_empssl6_39.yaml 
python main_knn.py --config-path ./configs/knn4/ --config-name default_empssl6_40.yaml 
python main_knn.py --config-path ./configs/knn4/ --config-name default_empssl6_41.yaml 
python main_knn.py --config-path ./configs/knn4/ --config-name default_empssl6_42.yaml 
python main_knn.py --config-path ./configs/knn4/ --config-name default_empssl6_43.yaml 
python main_knn.py --config-path ./configs/knn4/ --config-name default_empssl6_44.yaml 
python main_knn.py --config-path ./configs/knn4/ --config-name default_empssl6_45.yaml 
python main_knn.py --config-path ./configs/knn4/ --config-name default_empssl6_46.yaml 
python main_knn.py --config-path ./configs/knn4/ --config-name default_empssl6_47.yaml 
python main_knn.py --config-path ./configs/knn4/ --config-name default_empssl6_48.yaml 
python main_knn.py --config-path ./configs/knn4/ --config-name default_empssl6_49.yaml 
python main_knn.py --config-path ./configs/knn4/ --config-name default_empssl6_50.yaml 
python main_knn.py --config-path ./configs/knn4/ --config-name default_empssl6_51.yaml 
python main_knn.py --config-path ./configs/knn4/ --config-name default_empssl6_52.yaml 
python main_knn.py --config-path ./configs/knn4/ --config-name default_empssl6_53.yaml 
python main_knn.py --config-path ./configs/knn4/ --config-name default_empssl6_54.yaml 
python main_knn.py --config-path ./configs/knn4/ --config-name default_empssl6_55.yaml 
python main_knn.py --config-path ./configs/knn4/ --config-name default_empssl6_56.yaml 
python main_knn.py --config-path ./configs/knn4/ --config-name default_empssl6_57.yaml 
python main_knn.py --config-path ./configs/knn4/ --config-name default_empssl6_58.yaml 
python main_knn.py --config-path ./configs/knn4/ --config-name default_empssl6_59.yaml 
python main_knn.py --config-path ./configs/knn4/ --config-name default_empssl6_60.yaml 
python main_knn.py --config-path ./configs/knn4/ --config-name default_empssl6_61.yaml 
python main_knn.py --config-path ./configs/knn4/ --config-name default_empssl6_62.yaml 
python main_knn.py --config-path ./configs/knn4/ --config-name default_empssl6_63.yaml 
python main_knn.py --config-path ./configs/knn4/ --config-name default_empssl6_64.yaml 
python main_knn.py --config-path ./configs/knn4/ --config-name default_empssl6_65.yaml 
python main_knn.py --config-path ./configs/knn4/ --config-name default_empssl6_66.yaml 
python main_knn.py --config-path ./configs/knn4/ --config-name default_empssl6_67.yaml 
python main_knn.py --config-path ./configs/knn4/ --config-name default_empssl6_68.yaml 
python main_knn.py --config-path ./configs/knn4/ --config-name default_empssl6_69.yaml 
python main_knn.py --config-path ./configs/knn4/ --config-name default_empssl6_70.yaml 
python main_knn.py --config-path ./configs/knn4/ --config-name default_empssl6_71.yaml 
python main_knn.py --config-path ./configs/knn4/ --config-name default_empssl6_72.yaml 
python main_knn.py --config-path ./configs/knn4/ --config-name default_empssl6_73.yaml 
python main_knn.py --config-path ./configs/knn4/ --config-name default_empssl6_74.yaml 
python main_knn.py --config-path ./configs/knn4/ --config-name default_empssl6_75.yaml 
python main_knn.py --config-path ./configs/knn4/ --config-name default_empssl6_76.yaml 
python main_knn.py --config-path ./configs/knn4/ --config-name default_empssl6_77.yaml 
python main_knn.py --config-path ./configs/knn4/ --config-name default_empssl6_78.yaml 
python main_knn.py --config-path ./configs/knn4/ --config-name default_empssl6_79.yaml 
python main_knn.py --config-path ./configs/knn4/ --config-name default_empssl6_80.yaml 
python main_knn.py --config-path ./configs/knn4/ --config-name default_empssl6_81.yaml 
python main_knn.py --config-path ./configs/knn4/ --config-name default_empssl6_82.yaml 
python main_knn.py --config-path ./configs/knn4/ --config-name default_empssl6_83.yaml 
python main_knn.py --config-path ./configs/knn4/ --config-name default_empssl6_84.yaml 
python main_knn.py --config-path ./configs/knn4/ --config-name default_empssl6_85.yaml 
python main_knn.py --config-path ./configs/knn4/ --config-name default_empssl6_86.yaml 
python main_knn.py --config-path ./configs/knn4/ --config-name default_empssl6_87.yaml 
python main_knn.py --config-path ./configs/knn4/ --config-name default_empssl6_88.yaml 
python main_knn.py --config-path ./configs/knn4/ --config-name default_empssl6_89.yaml 
python main_knn.py --config-path ./configs/knn4/ --config-name default_empssl6_90.yaml 
python main_knn.py --config-path ./configs/knn4/ --config-name default_empssl6_91.yaml 
python main_knn.py --config-path ./configs/knn4/ --config-name default_empssl6_92.yaml 
python main_knn.py --config-path ./configs/knn4/ --config-name default_empssl6_93.yaml 
python main_knn.py --config-path ./configs/knn4/ --config-name default_empssl6_94.yaml 
python main_knn.py --config-path ./configs/knn4/ --config-name default_empssl6_95.yaml 
python main_knn.py --config-path ./configs/knn4/ --config-name default_empssl6_96.yaml 
python main_knn.py --config-path ./configs/knn4/ --config-name default_empssl6_97.yaml 
python main_knn.py --config-path ./configs/knn4/ --config-name default_empssl6_98.yaml 
python main_knn.py --config-path ./configs/knn4/ --config-name default_empssl6_99.yaml 
python main_knn.py --config-path ./configs/knn4/ --config-name default_empssl6_100.yaml 
python main_knn.py --config-path ./configs/knn4/ --config-name default_empssl6_101.yaml 
python main_knn.py --config-path ./configs/knn4/ --config-name default_empssl6_102.yaml 
python main_knn.py --config-path ./configs/knn4/ --config-name default_empssl6_103.yaml 
python main_knn.py --config-path ./configs/knn4/ --config-name default_empssl6_104.yaml 
python main_knn.py --config-path ./configs/knn4/ --config-name default_empssl6_105.yaml 
python main_knn.py --config-path ./configs/knn4/ --config-name default_empssl6_106.yaml 
python main_knn.py --config-path ./configs/knn4/ --config-name default_empssl6_107.yaml 
python main_knn.py --config-path ./configs/knn4/ --config-name default_empssl6_108.yaml 
python main_knn.py --config-path ./configs/knn4/ --config-name default_empssl6_109.yaml 
python main_knn.py --config-path ./configs/knn4/ --config-name default_empssl6_110.yaml 
python main_knn.py --config-path ./configs/knn4/ --config-name default_empssl6_111.yaml 
python main_knn.py --config-path ./configs/knn4/ --config-name default_empssl6_112.yaml 
python main_knn.py --config-path ./configs/knn4/ --config-name default_empssl6_113.yaml 
python main_knn.py --config-path ./configs/knn4/ --config-name default_empssl6_114.yaml 
python main_knn.py --config-path ./configs/knn4/ --config-name default_empssl6_115.yaml 
python main_knn.py --config-path ./configs/knn4/ --config-name default_empssl6_116.yaml 
python main_knn.py --config-path ./configs/knn4/ --config-name default_empssl6_117.yaml 
python main_knn.py --config-path ./configs/knn4/ --config-name default_empssl6_118.yaml 
python main_knn.py --config-path ./configs/knn4/ --config-name default_empssl6_119.yaml 
python main_knn.py --config-path ./configs/knn4/ --config-name default_empssl6_120.yaml 
python main_knn.py --config-path ./configs/knn4/ --config-name default_empssl6_121.yaml 
python main_knn.py --config-path ./configs/knn4/ --config-name default_empssl6_122.yaml 
python main_knn.py --config-path ./configs/knn4/ --config-name default_empssl6_123.yaml 
python main_knn.py --config-path ./configs/knn4/ --config-name default_empssl6_124.yaml 
python main_knn.py --config-path ./configs/knn4/ --config-name default_empssl6_125.yaml 
python main_knn.py --config-path ./configs/knn4/ --config-name default_empssl6_126.yaml 
python main_knn.py --config-path ./configs/knn4/ --config-name default_empssl6_127.yaml 
python main_knn.py --config-path ./configs/knn4/ --config-name default_empssl6_128.yaml 
python main_knn.py --config-path ./configs/knn4/ --config-name default_empssl6_129.yaml 
python main_knn.py --config-path ./configs/knn4/ --config-name default_empssl6_130.yaml 
python main_knn.py --config-path ./configs/knn4/ --config-name default_empssl6_131.yaml 
python main_knn.py --config-path ./configs/knn4/ --config-name default_empssl6_132.yaml 
python main_knn.py --config-path ./configs/knn4/ --config-name default_empssl6_133.yaml 
python main_knn.py --config-path ./configs/knn4/ --config-name default_empssl6_134.yaml 
python main_knn.py --config-path ./configs/knn4/ --config-name default_empssl6_135.yaml 
python main_knn.py --config-path ./configs/knn4/ --config-name default_empssl6_136.yaml 
python main_knn.py --config-path ./configs/knn4/ --config-name default_empssl6_137.yaml 
python main_knn.py --config-path ./configs/knn4/ --config-name default_empssl6_138.yaml 
python main_knn.py --config-path ./configs/knn4/ --config-name default_empssl6_139.yaml 
python main_knn.py --config-path ./configs/knn4/ --config-name default_empssl6_140.yaml 
python main_knn.py --config-path ./configs/knn4/ --config-name default_empssl6_141.yaml 
python main_knn.py --config-path ./configs/knn4/ --config-name default_empssl6_142.yaml 
python main_knn.py --config-path ./configs/knn4/ --config-name default_empssl6_143.yaml 
python main_knn.py --config-path ./configs/knn4/ --config-name default_empssl6_144.yaml 
python main_knn.py --config-path ./configs/knn4/ --config-name default_empssl6_145.yaml 
python main_knn.py --config-path ./configs/knn4/ --config-name default_empssl6_146.yaml 
python main_knn.py --config-path ./configs/knn4/ --config-name default_empssl6_147.yaml 
python main_knn.py --config-path ./configs/knn4/ --config-name default_empssl6_148.yaml 
python main_knn.py --config-path ./configs/knn4/ --config-name default_empssl6_149.yaml 
python main_knn.py --config-path ./configs/knn4/ --config-name default_empssl6_150.yaml 
python main_knn.py --config-path ./configs/knn4/ --config-name default_empssl6_151.yaml 
python main_knn.py --config-path ./configs/knn4/ --config-name default_empssl6_152.yaml 
python main_knn.py --config-path ./configs/knn4/ --config-name default_empssl6_153.yaml 
python main_knn.py --config-path ./configs/knn4/ --config-name default_empssl6_154.yaml 
python main_knn.py --config-path ./configs/knn4/ --config-name default_empssl6_155.yaml 
python main_knn.py --config-path ./configs/knn4/ --config-name default_empssl6_156.yaml 
python main_knn.py --config-path ./configs/knn4/ --config-name default_empssl6_157.yaml 
python main_knn.py --config-path ./configs/knn4/ --config-name default_empssl6_158.yaml 
python main_knn.py --config-path ./configs/knn4/ --config-name default_empssl6_159.yaml 
python main_knn.py --config-path ./configs/knn4/ --config-name default_empssl6_160.yaml 
python main_knn.py --config-path ./configs/knn4/ --config-name default_empssl6_161.yaml 
python main_knn.py --config-path ./configs/knn4/ --config-name default_empssl6_162.yaml 
python main_knn.py --config-path ./configs/knn4/ --config-name default_empssl6_163.yaml 
python main_knn.py --config-path ./configs/knn4/ --config-name default_empssl6_164.yaml 
python main_knn.py --config-path ./configs/knn4/ --config-name default_empssl6_165.yaml 
python main_knn.py --config-path ./configs/knn4/ --config-name default_empssl6_166.yaml 
python main_knn.py --config-path ./configs/knn4/ --config-name default_empssl6_167.yaml 
python main_knn.py --config-path ./configs/knn4/ --config-name default_empssl6_168.yaml 
python main_knn.py --config-path ./configs/knn4/ --config-name default_empssl6_169.yaml 
python main_knn.py --config-path ./configs/knn4/ --config-name default_empssl6_170.yaml 
python main_knn.py --config-path ./configs/knn4/ --config-name default_empssl6_171.yaml 
python main_knn.py --config-path ./configs/knn4/ --config-name default_empssl6_172.yaml 
python main_knn.py --config-path ./configs/knn4/ --config-name default_empssl6_173.yaml 
python main_knn.py --config-path ./configs/knn4/ --config-name default_empssl6_174.yaml 
python main_knn.py --config-path ./configs/knn4/ --config-name default_empssl6_175.yaml 
python main_knn.py --config-path ./configs/knn4/ --config-name default_empssl6_176.yaml 
python main_knn.py --config-path ./configs/knn4/ --config-name default_empssl6_177.yaml 
python main_knn.py --config-path ./configs/knn4/ --config-name default_empssl6_178.yaml 
python main_knn.py --config-path ./configs/knn4/ --config-name default_empssl6_179.yaml 
python main_knn.py --config-path ./configs/knn4/ --config-name default_empssl6_180.yaml 
python main_knn.py --config-path ./configs/knn4/ --config-name default_empssl6_181.yaml 
python main_knn.py --config-path ./configs/knn4/ --config-name default_empssl6_182.yaml 
python main_knn.py --config-path ./configs/knn4/ --config-name default_empssl6_183.yaml 
python main_knn.py --config-path ./configs/knn4/ --config-name default_empssl6_184.yaml 
python main_knn.py --config-path ./configs/knn4/ --config-name default_empssl6_185.yaml 
python main_knn.py --config-path ./configs/knn4/ --config-name default_empssl6_186.yaml 
python main_knn.py --config-path ./configs/knn4/ --config-name default_empssl6_187.yaml 
python main_knn.py --config-path ./configs/knn4/ --config-name default_empssl6_188.yaml 
python main_knn.py --config-path ./configs/knn4/ --config-name default_empssl6_189.yaml 
python main_knn.py --config-path ./configs/knn4/ --config-name default_empssl6_190.yaml 
python main_knn.py --config-path ./configs/knn4/ --config-name default_empssl6_191.yaml 
python main_knn.py --config-path ./configs/knn4/ --config-name default_empssl6_192.yaml 
python main_knn.py --config-path ./configs/knn4/ --config-name default_empssl6_193.yaml 
python main_knn.py --config-path ./configs/knn4/ --config-name default_empssl6_194.yaml 
python main_knn.py --config-path ./configs/knn4/ --config-name default_empssl6_195.yaml 
python main_knn.py --config-path ./configs/knn4/ --config-name default_empssl6_196.yaml 
python main_knn.py --config-path ./configs/knn4/ --config-name default_empssl6_197.yaml 
python main_knn.py --config-path ./configs/knn4/ --config-name default_empssl6_198.yaml 
python main_knn.py --config-path ./configs/knn4/ --config-name default_empssl6_199.yaml 
