export CUDA_VISIBLE_DEVICES="1"


python main_knn.py --config-path ./configs/knn5/ --config-name default_minred4_0.yaml 
python main_knn.py --config-path ./configs/knn5/ --config-name default_minred4_1.yaml 
python main_knn.py --config-path ./configs/knn5/ --config-name default_minred4_2.yaml 
python main_knn.py --config-path ./configs/knn5/ --config-name default_minred4_3.yaml 
python main_knn.py --config-path ./configs/knn5/ --config-name default_minred4_4.yaml 
python main_knn.py --config-path ./configs/knn5/ --config-name default_minred4_5.yaml 
python main_knn.py --config-path ./configs/knn5/ --config-name default_minred4_6.yaml 
python main_knn.py --config-path ./configs/knn5/ --config-name default_minred4_7.yaml 
python main_knn.py --config-path ./configs/knn5/ --config-name default_minred4_8.yaml 
python main_knn.py --config-path ./configs/knn5/ --config-name default_minred4_9.yaml 
python main_knn.py --config-path ./configs/knn5/ --config-name default_minred4_10.yaml 
python main_knn.py --config-path ./configs/knn5/ --config-name default_minred4_11.yaml 
python main_knn.py --config-path ./configs/knn5/ --config-name default_minred4_12.yaml 
python main_knn.py --config-path ./configs/knn5/ --config-name default_minred4_13.yaml 
python main_knn.py --config-path ./configs/knn5/ --config-name default_minred4_14.yaml 
python main_knn.py --config-path ./configs/knn5/ --config-name default_minred4_15.yaml 
python main_knn.py --config-path ./configs/knn5/ --config-name default_minred4_16.yaml 
python main_knn.py --config-path ./configs/knn5/ --config-name default_minred4_17.yaml 
python main_knn.py --config-path ./configs/knn5/ --config-name default_minred4_18.yaml 
python main_knn.py --config-path ./configs/knn5/ --config-name default_minred4_19.yaml 
python main_knn.py --config-path ./configs/knn5/ --config-name default_minred4_20.yaml 
python main_knn.py --config-path ./configs/knn5/ --config-name default_minred4_21.yaml 
python main_knn.py --config-path ./configs/knn5/ --config-name default_minred4_22.yaml 
python main_knn.py --config-path ./configs/knn5/ --config-name default_minred4_23.yaml 
python main_knn.py --config-path ./configs/knn5/ --config-name default_minred4_24.yaml 
python main_knn.py --config-path ./configs/knn5/ --config-name default_minred4_25.yaml 
python main_knn.py --config-path ./configs/knn5/ --config-name default_minred4_26.yaml 
python main_knn.py --config-path ./configs/knn5/ --config-name default_minred4_27.yaml 
python main_knn.py --config-path ./configs/knn5/ --config-name default_minred4_28.yaml 
python main_knn.py --config-path ./configs/knn5/ --config-name default_minred4_29.yaml 
python main_knn.py --config-path ./configs/knn5/ --config-name default_minred4_30.yaml 
python main_knn.py --config-path ./configs/knn5/ --config-name default_minred4_31.yaml 
python main_knn.py --config-path ./configs/knn5/ --config-name default_minred4_32.yaml 
python main_knn.py --config-path ./configs/knn5/ --config-name default_minred4_33.yaml 
python main_knn.py --config-path ./configs/knn5/ --config-name default_minred4_34.yaml 
python main_knn.py --config-path ./configs/knn5/ --config-name default_minred4_35.yaml 
python main_knn.py --config-path ./configs/knn5/ --config-name default_minred4_36.yaml 
python main_knn.py --config-path ./configs/knn5/ --config-name default_minred4_37.yaml 
python main_knn.py --config-path ./configs/knn5/ --config-name default_minred4_38.yaml 
python main_knn.py --config-path ./configs/knn5/ --config-name default_minred4_39.yaml 
python main_knn.py --config-path ./configs/knn5/ --config-name default_minred4_40.yaml 
python main_knn.py --config-path ./configs/knn5/ --config-name default_minred4_41.yaml 
python main_knn.py --config-path ./configs/knn5/ --config-name default_minred4_42.yaml 
python main_knn.py --config-path ./configs/knn5/ --config-name default_minred4_43.yaml 
python main_knn.py --config-path ./configs/knn5/ --config-name default_minred4_44.yaml 
python main_knn.py --config-path ./configs/knn5/ --config-name default_minred4_45.yaml 
python main_knn.py --config-path ./configs/knn5/ --config-name default_minred4_46.yaml 
python main_knn.py --config-path ./configs/knn5/ --config-name default_minred4_47.yaml 
python main_knn.py --config-path ./configs/knn5/ --config-name default_minred4_48.yaml 
python main_knn.py --config-path ./configs/knn5/ --config-name default_minred4_49.yaml 
python main_knn.py --config-path ./configs/knn5/ --config-name default_minred4_50.yaml 
python main_knn.py --config-path ./configs/knn5/ --config-name default_minred4_51.yaml 
python main_knn.py --config-path ./configs/knn5/ --config-name default_minred4_52.yaml 
python main_knn.py --config-path ./configs/knn5/ --config-name default_minred4_53.yaml 
python main_knn.py --config-path ./configs/knn5/ --config-name default_minred4_54.yaml 
python main_knn.py --config-path ./configs/knn5/ --config-name default_minred4_55.yaml 
python main_knn.py --config-path ./configs/knn5/ --config-name default_minred4_56.yaml 
python main_knn.py --config-path ./configs/knn5/ --config-name default_minred4_57.yaml 
python main_knn.py --config-path ./configs/knn5/ --config-name default_minred4_58.yaml 
python main_knn.py --config-path ./configs/knn5/ --config-name default_minred4_59.yaml 
python main_knn.py --config-path ./configs/knn5/ --config-name default_minred4_60.yaml 
python main_knn.py --config-path ./configs/knn5/ --config-name default_minred4_61.yaml 
python main_knn.py --config-path ./configs/knn5/ --config-name default_minred4_62.yaml 
python main_knn.py --config-path ./configs/knn5/ --config-name default_minred4_63.yaml 
python main_knn.py --config-path ./configs/knn5/ --config-name default_minred4_64.yaml 
python main_knn.py --config-path ./configs/knn5/ --config-name default_minred4_65.yaml 
python main_knn.py --config-path ./configs/knn5/ --config-name default_minred4_66.yaml 
python main_knn.py --config-path ./configs/knn5/ --config-name default_minred4_67.yaml 
python main_knn.py --config-path ./configs/knn5/ --config-name default_minred4_68.yaml 
python main_knn.py --config-path ./configs/knn5/ --config-name default_minred4_69.yaml 
python main_knn.py --config-path ./configs/knn5/ --config-name default_minred4_70.yaml 
python main_knn.py --config-path ./configs/knn5/ --config-name default_minred4_71.yaml 
python main_knn.py --config-path ./configs/knn5/ --config-name default_minred4_72.yaml 
python main_knn.py --config-path ./configs/knn5/ --config-name default_minred4_73.yaml 
python main_knn.py --config-path ./configs/knn5/ --config-name default_minred4_74.yaml 
python main_knn.py --config-path ./configs/knn5/ --config-name default_minred4_75.yaml 
python main_knn.py --config-path ./configs/knn5/ --config-name default_minred4_76.yaml 
python main_knn.py --config-path ./configs/knn5/ --config-name default_minred4_77.yaml 
python main_knn.py --config-path ./configs/knn5/ --config-name default_minred4_78.yaml 
python main_knn.py --config-path ./configs/knn5/ --config-name default_minred4_79.yaml 
python main_knn.py --config-path ./configs/knn5/ --config-name default_minred4_80.yaml 
python main_knn.py --config-path ./configs/knn5/ --config-name default_minred4_81.yaml 
python main_knn.py --config-path ./configs/knn5/ --config-name default_minred4_82.yaml 
python main_knn.py --config-path ./configs/knn5/ --config-name default_minred4_83.yaml 
python main_knn.py --config-path ./configs/knn5/ --config-name default_minred4_84.yaml 
python main_knn.py --config-path ./configs/knn5/ --config-name default_minred4_85.yaml 
python main_knn.py --config-path ./configs/knn5/ --config-name default_minred4_86.yaml 
python main_knn.py --config-path ./configs/knn5/ --config-name default_minred4_87.yaml 
python main_knn.py --config-path ./configs/knn5/ --config-name default_minred4_88.yaml 
python main_knn.py --config-path ./configs/knn5/ --config-name default_minred4_89.yaml 
python main_knn.py --config-path ./configs/knn5/ --config-name default_minred4_90.yaml 
python main_knn.py --config-path ./configs/knn5/ --config-name default_minred4_91.yaml 
python main_knn.py --config-path ./configs/knn5/ --config-name default_minred4_92.yaml 
python main_knn.py --config-path ./configs/knn5/ --config-name default_minred4_93.yaml 
python main_knn.py --config-path ./configs/knn5/ --config-name default_minred4_94.yaml 
python main_knn.py --config-path ./configs/knn5/ --config-name default_minred4_95.yaml 
python main_knn.py --config-path ./configs/knn5/ --config-name default_minred4_96.yaml 
python main_knn.py --config-path ./configs/knn5/ --config-name default_minred4_97.yaml 
python main_knn.py --config-path ./configs/knn5/ --config-name default_minred4_98.yaml 
python main_knn.py --config-path ./configs/knn5/ --config-name default_minred4_99.yaml 
python main_knn.py --config-path ./configs/knn5/ --config-name default_minred4_100.yaml 
python main_knn.py --config-path ./configs/knn5/ --config-name default_minred4_101.yaml 
python main_knn.py --config-path ./configs/knn5/ --config-name default_minred4_102.yaml 
python main_knn.py --config-path ./configs/knn5/ --config-name default_minred4_103.yaml 
python main_knn.py --config-path ./configs/knn5/ --config-name default_minred4_104.yaml 
python main_knn.py --config-path ./configs/knn5/ --config-name default_minred4_105.yaml 
python main_knn.py --config-path ./configs/knn5/ --config-name default_minred4_106.yaml 
python main_knn.py --config-path ./configs/knn5/ --config-name default_minred4_107.yaml 
python main_knn.py --config-path ./configs/knn5/ --config-name default_minred4_108.yaml 
python main_knn.py --config-path ./configs/knn5/ --config-name default_minred4_109.yaml 
python main_knn.py --config-path ./configs/knn5/ --config-name default_minred4_110.yaml 
python main_knn.py --config-path ./configs/knn5/ --config-name default_minred4_111.yaml 
python main_knn.py --config-path ./configs/knn5/ --config-name default_minred4_112.yaml 
python main_knn.py --config-path ./configs/knn5/ --config-name default_minred4_113.yaml 
python main_knn.py --config-path ./configs/knn5/ --config-name default_minred4_114.yaml 
python main_knn.py --config-path ./configs/knn5/ --config-name default_minred4_115.yaml 
python main_knn.py --config-path ./configs/knn5/ --config-name default_minred4_116.yaml 
python main_knn.py --config-path ./configs/knn5/ --config-name default_minred4_117.yaml 
python main_knn.py --config-path ./configs/knn5/ --config-name default_minred4_118.yaml 
python main_knn.py --config-path ./configs/knn5/ --config-name default_minred4_119.yaml 
python main_knn.py --config-path ./configs/knn5/ --config-name default_minred4_120.yaml 
python main_knn.py --config-path ./configs/knn5/ --config-name default_minred4_121.yaml 
python main_knn.py --config-path ./configs/knn5/ --config-name default_minred4_122.yaml 
python main_knn.py --config-path ./configs/knn5/ --config-name default_minred4_123.yaml 
python main_knn.py --config-path ./configs/knn5/ --config-name default_minred4_124.yaml 
python main_knn.py --config-path ./configs/knn5/ --config-name default_minred4_125.yaml 
python main_knn.py --config-path ./configs/knn5/ --config-name default_minred4_126.yaml 
python main_knn.py --config-path ./configs/knn5/ --config-name default_minred4_127.yaml 
python main_knn.py --config-path ./configs/knn5/ --config-name default_minred4_128.yaml 
python main_knn.py --config-path ./configs/knn5/ --config-name default_minred4_129.yaml 
python main_knn.py --config-path ./configs/knn5/ --config-name default_minred4_130.yaml 
python main_knn.py --config-path ./configs/knn5/ --config-name default_minred4_131.yaml 
python main_knn.py --config-path ./configs/knn5/ --config-name default_minred4_132.yaml 
python main_knn.py --config-path ./configs/knn5/ --config-name default_minred4_133.yaml 
python main_knn.py --config-path ./configs/knn5/ --config-name default_minred4_134.yaml 
python main_knn.py --config-path ./configs/knn5/ --config-name default_minred4_135.yaml 
python main_knn.py --config-path ./configs/knn5/ --config-name default_minred4_136.yaml 
python main_knn.py --config-path ./configs/knn5/ --config-name default_minred4_137.yaml 
python main_knn.py --config-path ./configs/knn5/ --config-name default_minred4_138.yaml 
python main_knn.py --config-path ./configs/knn5/ --config-name default_minred4_139.yaml 
python main_knn.py --config-path ./configs/knn5/ --config-name default_minred4_140.yaml 
python main_knn.py --config-path ./configs/knn5/ --config-name default_minred4_141.yaml 
python main_knn.py --config-path ./configs/knn5/ --config-name default_minred4_142.yaml 
python main_knn.py --config-path ./configs/knn5/ --config-name default_minred4_143.yaml 
python main_knn.py --config-path ./configs/knn5/ --config-name default_minred4_144.yaml 
python main_knn.py --config-path ./configs/knn5/ --config-name default_minred4_145.yaml 
python main_knn.py --config-path ./configs/knn5/ --config-name default_minred4_146.yaml 
python main_knn.py --config-path ./configs/knn5/ --config-name default_minred4_147.yaml 
python main_knn.py --config-path ./configs/knn5/ --config-name default_minred4_148.yaml 
python main_knn.py --config-path ./configs/knn5/ --config-name default_minred4_149.yaml 
python main_knn.py --config-path ./configs/knn5/ --config-name default_minred4_150.yaml 
python main_knn.py --config-path ./configs/knn5/ --config-name default_minred4_151.yaml 
python main_knn.py --config-path ./configs/knn5/ --config-name default_minred4_152.yaml 
python main_knn.py --config-path ./configs/knn5/ --config-name default_minred4_153.yaml 
python main_knn.py --config-path ./configs/knn5/ --config-name default_minred4_154.yaml 
python main_knn.py --config-path ./configs/knn5/ --config-name default_minred4_155.yaml 
python main_knn.py --config-path ./configs/knn5/ --config-name default_minred4_156.yaml 
python main_knn.py --config-path ./configs/knn5/ --config-name default_minred4_157.yaml 
python main_knn.py --config-path ./configs/knn5/ --config-name default_minred4_158.yaml 
python main_knn.py --config-path ./configs/knn5/ --config-name default_minred4_159.yaml 
python main_knn.py --config-path ./configs/knn5/ --config-name default_minred4_160.yaml 
python main_knn.py --config-path ./configs/knn5/ --config-name default_minred4_161.yaml 
python main_knn.py --config-path ./configs/knn5/ --config-name default_minred4_162.yaml 
python main_knn.py --config-path ./configs/knn5/ --config-name default_minred4_163.yaml 
python main_knn.py --config-path ./configs/knn5/ --config-name default_minred4_164.yaml 
python main_knn.py --config-path ./configs/knn5/ --config-name default_minred4_165.yaml 
python main_knn.py --config-path ./configs/knn5/ --config-name default_minred4_166.yaml 
python main_knn.py --config-path ./configs/knn5/ --config-name default_minred4_167.yaml 
python main_knn.py --config-path ./configs/knn5/ --config-name default_minred4_168.yaml 
python main_knn.py --config-path ./configs/knn5/ --config-name default_minred4_169.yaml 
python main_knn.py --config-path ./configs/knn5/ --config-name default_minred4_170.yaml 
python main_knn.py --config-path ./configs/knn5/ --config-name default_minred4_171.yaml 
python main_knn.py --config-path ./configs/knn5/ --config-name default_minred4_172.yaml 
python main_knn.py --config-path ./configs/knn5/ --config-name default_minred4_173.yaml 
python main_knn.py --config-path ./configs/knn5/ --config-name default_minred4_174.yaml 
python main_knn.py --config-path ./configs/knn5/ --config-name default_minred4_175.yaml 
python main_knn.py --config-path ./configs/knn5/ --config-name default_minred4_176.yaml 
python main_knn.py --config-path ./configs/knn5/ --config-name default_minred4_177.yaml 
python main_knn.py --config-path ./configs/knn5/ --config-name default_minred4_178.yaml 
python main_knn.py --config-path ./configs/knn5/ --config-name default_minred4_179.yaml 
python main_knn.py --config-path ./configs/knn5/ --config-name default_minred4_180.yaml 
python main_knn.py --config-path ./configs/knn5/ --config-name default_minred4_181.yaml 
python main_knn.py --config-path ./configs/knn5/ --config-name default_minred4_182.yaml 
python main_knn.py --config-path ./configs/knn5/ --config-name default_minred4_183.yaml 
python main_knn.py --config-path ./configs/knn5/ --config-name default_minred4_184.yaml 
python main_knn.py --config-path ./configs/knn5/ --config-name default_minred4_185.yaml 
python main_knn.py --config-path ./configs/knn5/ --config-name default_minred4_186.yaml 
python main_knn.py --config-path ./configs/knn5/ --config-name default_minred4_187.yaml 
python main_knn.py --config-path ./configs/knn5/ --config-name default_minred4_188.yaml 
python main_knn.py --config-path ./configs/knn5/ --config-name default_minred4_189.yaml 
python main_knn.py --config-path ./configs/knn5/ --config-name default_minred4_190.yaml 
python main_knn.py --config-path ./configs/knn5/ --config-name default_minred4_191.yaml 
python main_knn.py --config-path ./configs/knn5/ --config-name default_minred4_192.yaml 
python main_knn.py --config-path ./configs/knn5/ --config-name default_minred4_193.yaml 
python main_knn.py --config-path ./configs/knn5/ --config-name default_minred4_194.yaml 
python main_knn.py --config-path ./configs/knn5/ --config-name default_minred4_195.yaml 
python main_knn.py --config-path ./configs/knn5/ --config-name default_minred4_196.yaml 
python main_knn.py --config-path ./configs/knn5/ --config-name default_minred4_197.yaml 
python main_knn.py --config-path ./configs/knn5/ --config-name default_minred4_198.yaml 
python main_knn.py --config-path ./configs/knn5/ --config-name default_minred4_199.yaml 
