export CUDA_VISIBLE_DEVICES="3"

python main_knn.py --config-path ./configs/knn2/ --config-name default_ours5_0.yaml 
python main_knn.py --config-path ./configs/knn2/ --config-name default_ours5_1.yaml 
python main_knn.py --config-path ./configs/knn2/ --config-name default_ours5_2.yaml 
python main_knn.py --config-path ./configs/knn2/ --config-name default_ours5_3.yaml 
python main_knn.py --config-path ./configs/knn2/ --config-name default_ours5_4.yaml 
python main_knn.py --config-path ./configs/knn2/ --config-name default_ours5_5.yaml 
python main_knn.py --config-path ./configs/knn2/ --config-name default_ours5_6.yaml 
python main_knn.py --config-path ./configs/knn2/ --config-name default_ours5_7.yaml 
python main_knn.py --config-path ./configs/knn2/ --config-name default_ours5_8.yaml 
python main_knn.py --config-path ./configs/knn2/ --config-name default_ours5_9.yaml 
python main_knn.py --config-path ./configs/knn2/ --config-name default_ours5_10.yaml 
python main_knn.py --config-path ./configs/knn2/ --config-name default_ours5_11.yaml 
python main_knn.py --config-path ./configs/knn2/ --config-name default_ours5_12.yaml 
python main_knn.py --config-path ./configs/knn2/ --config-name default_ours5_13.yaml 
python main_knn.py --config-path ./configs/knn2/ --config-name default_ours5_14.yaml 
python main_knn.py --config-path ./configs/knn2/ --config-name default_ours5_15.yaml 
python main_knn.py --config-path ./configs/knn2/ --config-name default_ours5_16.yaml 
python main_knn.py --config-path ./configs/knn2/ --config-name default_ours5_17.yaml 
python main_knn.py --config-path ./configs/knn2/ --config-name default_ours5_18.yaml 
python main_knn.py --config-path ./configs/knn2/ --config-name default_ours5_19.yaml 
python main_knn.py --config-path ./configs/knn2/ --config-name default_ours5_20.yaml 
python main_knn.py --config-path ./configs/knn2/ --config-name default_ours5_21.yaml 
python main_knn.py --config-path ./configs/knn2/ --config-name default_ours5_22.yaml 
python main_knn.py --config-path ./configs/knn2/ --config-name default_ours5_23.yaml 
python main_knn.py --config-path ./configs/knn2/ --config-name default_ours5_24.yaml 
python main_knn.py --config-path ./configs/knn2/ --config-name default_ours5_25.yaml 
python main_knn.py --config-path ./configs/knn2/ --config-name default_ours5_26.yaml 
python main_knn.py --config-path ./configs/knn2/ --config-name default_ours5_27.yaml 
python main_knn.py --config-path ./configs/knn2/ --config-name default_ours5_28.yaml 
python main_knn.py --config-path ./configs/knn2/ --config-name default_ours5_29.yaml 
python main_knn.py --config-path ./configs/knn2/ --config-name default_ours5_30.yaml 
python main_knn.py --config-path ./configs/knn2/ --config-name default_ours5_31.yaml 
python main_knn.py --config-path ./configs/knn2/ --config-name default_ours5_32.yaml 
python main_knn.py --config-path ./configs/knn2/ --config-name default_ours5_33.yaml 
python main_knn.py --config-path ./configs/knn2/ --config-name default_ours5_34.yaml 
python main_knn.py --config-path ./configs/knn2/ --config-name default_ours5_35.yaml 
python main_knn.py --config-path ./configs/knn2/ --config-name default_ours5_36.yaml 
python main_knn.py --config-path ./configs/knn2/ --config-name default_ours5_37.yaml 
python main_knn.py --config-path ./configs/knn2/ --config-name default_ours5_38.yaml 
python main_knn.py --config-path ./configs/knn2/ --config-name default_ours5_39.yaml 
python main_knn.py --config-path ./configs/knn2/ --config-name default_ours5_40.yaml 
python main_knn.py --config-path ./configs/knn2/ --config-name default_ours5_41.yaml 
python main_knn.py --config-path ./configs/knn2/ --config-name default_ours5_42.yaml 
python main_knn.py --config-path ./configs/knn2/ --config-name default_ours5_43.yaml 
python main_knn.py --config-path ./configs/knn2/ --config-name default_ours5_44.yaml 
python main_knn.py --config-path ./configs/knn2/ --config-name default_ours5_45.yaml 
python main_knn.py --config-path ./configs/knn2/ --config-name default_ours5_46.yaml 
python main_knn.py --config-path ./configs/knn2/ --config-name default_ours5_47.yaml 
python main_knn.py --config-path ./configs/knn2/ --config-name default_ours5_48.yaml 
python main_knn.py --config-path ./configs/knn2/ --config-name default_ours5_49.yaml 
python main_knn.py --config-path ./configs/knn2/ --config-name default_ours5_50.yaml 
python main_knn.py --config-path ./configs/knn2/ --config-name default_ours5_51.yaml 
python main_knn.py --config-path ./configs/knn2/ --config-name default_ours5_52.yaml 
python main_knn.py --config-path ./configs/knn2/ --config-name default_ours5_53.yaml 
python main_knn.py --config-path ./configs/knn2/ --config-name default_ours5_54.yaml 
python main_knn.py --config-path ./configs/knn2/ --config-name default_ours5_55.yaml 
python main_knn.py --config-path ./configs/knn2/ --config-name default_ours5_56.yaml 
python main_knn.py --config-path ./configs/knn2/ --config-name default_ours5_57.yaml 
python main_knn.py --config-path ./configs/knn2/ --config-name default_ours5_58.yaml 
python main_knn.py --config-path ./configs/knn2/ --config-name default_ours5_59.yaml 
python main_knn.py --config-path ./configs/knn2/ --config-name default_ours5_60.yaml 
python main_knn.py --config-path ./configs/knn2/ --config-name default_ours5_61.yaml 
python main_knn.py --config-path ./configs/knn2/ --config-name default_ours5_62.yaml 
python main_knn.py --config-path ./configs/knn2/ --config-name default_ours5_63.yaml 
python main_knn.py --config-path ./configs/knn2/ --config-name default_ours5_64.yaml 
python main_knn.py --config-path ./configs/knn2/ --config-name default_ours5_65.yaml 
python main_knn.py --config-path ./configs/knn2/ --config-name default_ours5_66.yaml 
python main_knn.py --config-path ./configs/knn2/ --config-name default_ours5_67.yaml 
python main_knn.py --config-path ./configs/knn2/ --config-name default_ours5_68.yaml 
python main_knn.py --config-path ./configs/knn2/ --config-name default_ours5_69.yaml 
python main_knn.py --config-path ./configs/knn2/ --config-name default_ours5_70.yaml 
python main_knn.py --config-path ./configs/knn2/ --config-name default_ours5_71.yaml 
python main_knn.py --config-path ./configs/knn2/ --config-name default_ours5_72.yaml 
python main_knn.py --config-path ./configs/knn2/ --config-name default_ours5_73.yaml 
python main_knn.py --config-path ./configs/knn2/ --config-name default_ours5_74.yaml 
python main_knn.py --config-path ./configs/knn2/ --config-name default_ours5_75.yaml 
python main_knn.py --config-path ./configs/knn2/ --config-name default_ours5_76.yaml 
python main_knn.py --config-path ./configs/knn2/ --config-name default_ours5_77.yaml 
python main_knn.py --config-path ./configs/knn2/ --config-name default_ours5_78.yaml 
python main_knn.py --config-path ./configs/knn2/ --config-name default_ours5_79.yaml 
python main_knn.py --config-path ./configs/knn2/ --config-name default_ours5_80.yaml 
python main_knn.py --config-path ./configs/knn2/ --config-name default_ours5_81.yaml 
python main_knn.py --config-path ./configs/knn2/ --config-name default_ours5_82.yaml 
python main_knn.py --config-path ./configs/knn2/ --config-name default_ours5_83.yaml 
python main_knn.py --config-path ./configs/knn2/ --config-name default_ours5_84.yaml 
python main_knn.py --config-path ./configs/knn2/ --config-name default_ours5_85.yaml 
python main_knn.py --config-path ./configs/knn2/ --config-name default_ours5_86.yaml 
python main_knn.py --config-path ./configs/knn2/ --config-name default_ours5_87.yaml 
python main_knn.py --config-path ./configs/knn2/ --config-name default_ours5_88.yaml 
python main_knn.py --config-path ./configs/knn2/ --config-name default_ours5_89.yaml 
python main_knn.py --config-path ./configs/knn2/ --config-name default_ours5_90.yaml 
python main_knn.py --config-path ./configs/knn2/ --config-name default_ours5_91.yaml 
python main_knn.py --config-path ./configs/knn2/ --config-name default_ours5_92.yaml 
python main_knn.py --config-path ./configs/knn2/ --config-name default_ours5_93.yaml 
python main_knn.py --config-path ./configs/knn2/ --config-name default_ours5_94.yaml 
python main_knn.py --config-path ./configs/knn2/ --config-name default_ours5_95.yaml 
python main_knn.py --config-path ./configs/knn2/ --config-name default_ours5_96.yaml 
python main_knn.py --config-path ./configs/knn2/ --config-name default_ours5_97.yaml 
python main_knn.py --config-path ./configs/knn2/ --config-name default_ours5_98.yaml 
python main_knn.py --config-path ./configs/knn2/ --config-name default_ours5_99.yaml 
python main_knn.py --config-path ./configs/knn2/ --config-name default_ours5_100.yaml 
python main_knn.py --config-path ./configs/knn2/ --config-name default_ours5_101.yaml 
python main_knn.py --config-path ./configs/knn2/ --config-name default_ours5_102.yaml 
python main_knn.py --config-path ./configs/knn2/ --config-name default_ours5_103.yaml 
python main_knn.py --config-path ./configs/knn2/ --config-name default_ours5_104.yaml 
python main_knn.py --config-path ./configs/knn2/ --config-name default_ours5_105.yaml 
python main_knn.py --config-path ./configs/knn2/ --config-name default_ours5_106.yaml 
python main_knn.py --config-path ./configs/knn2/ --config-name default_ours5_107.yaml 
python main_knn.py --config-path ./configs/knn2/ --config-name default_ours5_108.yaml 
python main_knn.py --config-path ./configs/knn2/ --config-name default_ours5_109.yaml 
python main_knn.py --config-path ./configs/knn2/ --config-name default_ours5_110.yaml 
python main_knn.py --config-path ./configs/knn2/ --config-name default_ours5_111.yaml 
python main_knn.py --config-path ./configs/knn2/ --config-name default_ours5_112.yaml 
python main_knn.py --config-path ./configs/knn2/ --config-name default_ours5_113.yaml 
python main_knn.py --config-path ./configs/knn2/ --config-name default_ours5_114.yaml 
python main_knn.py --config-path ./configs/knn2/ --config-name default_ours5_115.yaml 
python main_knn.py --config-path ./configs/knn2/ --config-name default_ours5_116.yaml 
python main_knn.py --config-path ./configs/knn2/ --config-name default_ours5_117.yaml 
python main_knn.py --config-path ./configs/knn2/ --config-name default_ours5_118.yaml 
python main_knn.py --config-path ./configs/knn2/ --config-name default_ours5_119.yaml 
python main_knn.py --config-path ./configs/knn2/ --config-name default_ours5_120.yaml 
python main_knn.py --config-path ./configs/knn2/ --config-name default_ours5_121.yaml 
python main_knn.py --config-path ./configs/knn2/ --config-name default_ours5_122.yaml 
python main_knn.py --config-path ./configs/knn2/ --config-name default_ours5_123.yaml 
python main_knn.py --config-path ./configs/knn2/ --config-name default_ours5_124.yaml 
python main_knn.py --config-path ./configs/knn2/ --config-name default_ours5_125.yaml 
python main_knn.py --config-path ./configs/knn2/ --config-name default_ours5_126.yaml 
python main_knn.py --config-path ./configs/knn2/ --config-name default_ours5_127.yaml 
python main_knn.py --config-path ./configs/knn2/ --config-name default_ours5_128.yaml 
python main_knn.py --config-path ./configs/knn2/ --config-name default_ours5_129.yaml 
python main_knn.py --config-path ./configs/knn2/ --config-name default_ours5_130.yaml 
python main_knn.py --config-path ./configs/knn2/ --config-name default_ours5_131.yaml 
python main_knn.py --config-path ./configs/knn2/ --config-name default_ours5_132.yaml 
python main_knn.py --config-path ./configs/knn2/ --config-name default_ours5_133.yaml 
python main_knn.py --config-path ./configs/knn2/ --config-name default_ours5_134.yaml 
python main_knn.py --config-path ./configs/knn2/ --config-name default_ours5_135.yaml 
python main_knn.py --config-path ./configs/knn2/ --config-name default_ours5_136.yaml 
python main_knn.py --config-path ./configs/knn2/ --config-name default_ours5_137.yaml 
python main_knn.py --config-path ./configs/knn2/ --config-name default_ours5_138.yaml 
python main_knn.py --config-path ./configs/knn2/ --config-name default_ours5_139.yaml 
python main_knn.py --config-path ./configs/knn2/ --config-name default_ours5_140.yaml 
python main_knn.py --config-path ./configs/knn2/ --config-name default_ours5_141.yaml 
python main_knn.py --config-path ./configs/knn2/ --config-name default_ours5_142.yaml 
python main_knn.py --config-path ./configs/knn2/ --config-name default_ours5_143.yaml 
python main_knn.py --config-path ./configs/knn2/ --config-name default_ours5_144.yaml 
python main_knn.py --config-path ./configs/knn2/ --config-name default_ours5_145.yaml 
python main_knn.py --config-path ./configs/knn2/ --config-name default_ours5_146.yaml 
python main_knn.py --config-path ./configs/knn2/ --config-name default_ours5_147.yaml 
python main_knn.py --config-path ./configs/knn2/ --config-name default_ours5_148.yaml 
python main_knn.py --config-path ./configs/knn2/ --config-name default_ours5_149.yaml 
python main_knn.py --config-path ./configs/knn2/ --config-name default_ours5_150.yaml 
python main_knn.py --config-path ./configs/knn2/ --config-name default_ours5_151.yaml 
python main_knn.py --config-path ./configs/knn2/ --config-name default_ours5_152.yaml 
python main_knn.py --config-path ./configs/knn2/ --config-name default_ours5_153.yaml 
python main_knn.py --config-path ./configs/knn2/ --config-name default_ours5_154.yaml 
python main_knn.py --config-path ./configs/knn2/ --config-name default_ours5_155.yaml 
python main_knn.py --config-path ./configs/knn2/ --config-name default_ours5_156.yaml 
python main_knn.py --config-path ./configs/knn2/ --config-name default_ours5_157.yaml 
python main_knn.py --config-path ./configs/knn2/ --config-name default_ours5_158.yaml 
python main_knn.py --config-path ./configs/knn2/ --config-name default_ours5_159.yaml 
python main_knn.py --config-path ./configs/knn2/ --config-name default_ours5_160.yaml 
python main_knn.py --config-path ./configs/knn2/ --config-name default_ours5_161.yaml 
python main_knn.py --config-path ./configs/knn2/ --config-name default_ours5_162.yaml 
python main_knn.py --config-path ./configs/knn2/ --config-name default_ours5_163.yaml 
python main_knn.py --config-path ./configs/knn2/ --config-name default_ours5_164.yaml 
python main_knn.py --config-path ./configs/knn2/ --config-name default_ours5_165.yaml 
python main_knn.py --config-path ./configs/knn2/ --config-name default_ours5_166.yaml 
python main_knn.py --config-path ./configs/knn2/ --config-name default_ours5_167.yaml 
python main_knn.py --config-path ./configs/knn2/ --config-name default_ours5_168.yaml 
python main_knn.py --config-path ./configs/knn2/ --config-name default_ours5_169.yaml 
python main_knn.py --config-path ./configs/knn2/ --config-name default_ours5_170.yaml 
python main_knn.py --config-path ./configs/knn2/ --config-name default_ours5_171.yaml 
python main_knn.py --config-path ./configs/knn2/ --config-name default_ours5_172.yaml 
python main_knn.py --config-path ./configs/knn2/ --config-name default_ours5_173.yaml 
python main_knn.py --config-path ./configs/knn2/ --config-name default_ours5_174.yaml 
python main_knn.py --config-path ./configs/knn2/ --config-name default_ours5_175.yaml 
python main_knn.py --config-path ./configs/knn2/ --config-name default_ours5_176.yaml 
python main_knn.py --config-path ./configs/knn2/ --config-name default_ours5_177.yaml 
python main_knn.py --config-path ./configs/knn2/ --config-name default_ours5_178.yaml 
python main_knn.py --config-path ./configs/knn2/ --config-name default_ours5_179.yaml 
python main_knn.py --config-path ./configs/knn2/ --config-name default_ours5_180.yaml 
python main_knn.py --config-path ./configs/knn2/ --config-name default_ours5_181.yaml 
python main_knn.py --config-path ./configs/knn2/ --config-name default_ours5_182.yaml 
python main_knn.py --config-path ./configs/knn2/ --config-name default_ours5_183.yaml 
python main_knn.py --config-path ./configs/knn2/ --config-name default_ours5_184.yaml 
python main_knn.py --config-path ./configs/knn2/ --config-name default_ours5_185.yaml 
python main_knn.py --config-path ./configs/knn2/ --config-name default_ours5_186.yaml 
python main_knn.py --config-path ./configs/knn2/ --config-name default_ours5_187.yaml 
python main_knn.py --config-path ./configs/knn2/ --config-name default_ours5_188.yaml 
python main_knn.py --config-path ./configs/knn2/ --config-name default_ours5_189.yaml 
python main_knn.py --config-path ./configs/knn2/ --config-name default_ours5_190.yaml 
python main_knn.py --config-path ./configs/knn2/ --config-name default_ours5_191.yaml 
python main_knn.py --config-path ./configs/knn2/ --config-name default_ours5_192.yaml 
python main_knn.py --config-path ./configs/knn2/ --config-name default_ours5_193.yaml 
python main_knn.py --config-path ./configs/knn2/ --config-name default_ours5_194.yaml 
python main_knn.py --config-path ./configs/knn2/ --config-name default_ours5_195.yaml 
python main_knn.py --config-path ./configs/knn2/ --config-name default_ours5_196.yaml 
python main_knn.py --config-path ./configs/knn2/ --config-name default_ours5_197.yaml 
python main_knn.py --config-path ./configs/knn2/ --config-name default_ours5_198.yaml 
python main_knn.py --config-path ./configs/knn2/ --config-name default_ours5_199.yaml 
