
# configファイルの保存先なので忘れず変更する
hydra:
  run:
    dir: outputs/empssl_baseline2

# 手法名
method: 
  name: "empssl"
  num_crops: 10
  lambda_sim: 200
  lambda_tcr: 1.0
  eps_tcr: 0.2


model:
  type: "resnet50"
  hidden_dim: 4096
  output_dim: 1024


dataset:
  type: "imagenet21k"
  num_classes: 13971
  data_folder: '/home/kouyou/datasets/'
  filelist: "/home/kouyou/make_dataset/kmeans_clustering_100/filelists/similar_order"
  # filelist: "/home/kouyou/ContinualLearning/kmeans_clustering_100/filelists4cluster/similar_order"
  size: 224
  drop_last: True 
  start_index: 0
  sharding: "interleave"


optimizer:
  train:
    learning_rate: 0.1
    weight_decay: 1e-4
    momentum: 0.9
    eta: 0.005
    batch_size: 128
    start_epoch: 0
    epochs: 1
    scheduler_type: "cos"
    scheduler_exit_decay: 0


continual:
  n_cls: 13971
  cls_per_task: [150,  419,  122,  876,  432,  228,  1623,  586,  395,  147,
                  36,   92,  168,  276,  327,   67,   215,   52,  124,   21, 
                  24,   97,  133,  139,   80,  427,    53,  221,   35,  261,
                 133,   52,   75,   95,   88,  180,   138,   31,  187,   44, 
                 124,  135,   54,   41,   65,  406,   202,   64,   64,   46, 
                  98,    7,   53,  178,  111,  190,    56,  103,  198,  146, 
                 122,  159,   26,   64,   99,   15,    68,   21,  139,   22, 
                  28,   26,   31,   46,  105,   69,    43,  176,   49,   33, 
                  40,   43,   25,   49,   16,   90,   115,  131,   34,   52, 
                  52,   13,   17,  117,  243,  116,    16,   31,  139,  101]
  n_task: 100
  buffer_type: "minred"
  buffer_size: 65536
  repeat: 3



linear:
  dataset: "imagenet21k"
  task_id: [6]
  n_task: 100
  num_workers: 10
  ckpt: "checkpoint_00001.0000.pth"
  train:
    batch_size: 1024
    epochs: 100
    learning_rate: 1.0
    momentum: 0.9
    weight_decay: 0
    schedule: [60, 80]
    eta: 0.005
    cos: True


detection:
  ckpt: "checkpoint_00001.0000.pth"
  num_classes: 91
  batch_size: 4
  eval_batch_size: 4
  num_workers: 8
  lr: 0.02
  momentum: 0.9
  weight_decay: 0.0001
  epochs: 12
  lr_milestones: [8, 11]
  lr_gamma: 0.1
  trainable_layers: 3
  use_amp: true
  print_freq: 20
  output_dir: "./logs/ours/detection_eval"
  random_horizontal_flip: 0.5
  resize_images: false
  min_size: 800
  max_size: 1333
  image_mean: [0.485, 0.456, 0.406]
  image_std: [0.229, 0.224, 0.225]



log:
  name: 
  base: "baseline2"
  model: "model"
  result: "result"
  base_path: 
  model_path: 
  explog_path: 
  mem_path: 
  result_path: 
  save_freq: 0.005
  save_freq_mints: 20
  print_freq: 10
  resume: True


ddp:
  local_rank: 
  use_ddp: 
  world_size: 

amp:
  use_amp: True
  dtype: "fp16"        # "fp16" か "bf16"（A100/H100 や RTX 40xx は bf16 推奨）
  grad_scaler: true    # bf16 のときは自動的に無視されます


seed: 777
date: 2025_1023
workers: 4


debug: False



