

# 手法名
method: 
  name: "ours"
  num_crops: 5
  lambda_mcc: 200
  lambda_tcr: 1.0
  temp_mcc: 0.07
  eps_tcr: 0.2


model:
  type: "resnet50"
  hidden_dim: 4096
  output_dim: 1024


dataset:
  type: "imagenet21k"
  num_classes: 15813
  data_folder: '/home/kouyou/datasets/'
  filelist: "/home/kouyou/datasets/ImageNet21K/filelists/kmeans_clustering_100/filelists/similar_order"
  size: 224
  drop_last: True
  start_index: 0
  sharding: "interleave"


optimizer:
  train:
    learning_rate: 0.1
    weight_decay: 1e-4
    momentum: 0.9
    eta: 0.005
    batch_size: 64
    start_epoch: 0
    epochs: 1
    scheduler_type: "cos"
    scheduler_exit_decay: 0


continual:
  n_cls: 15813
  cls_per_task: [92,  323,  217, 58,  942, 410, 105, 161, 142, 29,
                 132, 265,  175, 214, 551, 231, 253, 244, 243, 387,
                 156, 189,  54,  83,  86,  112, 872, 187, 78,  22,
                 97,  117,  145, 70,  67,  280, 149, 91,  158, 67,
                 36,  49,   48,  99,  235, 42,  49,  25,  56,  109, 
                 642, 1062, 428, 164, 162, 37,  58,  114, 150, 33, 
                 113, 22,   32,  400, 100, 56,  116, 92,  233, 154, 
                 128, 230,  137, 45,  90,  87,  77,  302, 113, 100, 
                 140, 29,   124, 11,  29,  45,  25,  35,  79,  141, 
                 30,  36,   60,  161, 33,  85,  46,  158, 49,  18]
  n_task: 1
  buffer_type: "minred"
  buffer_size: 4096
  repeat: 2


log:
  name: 
  base: "default-v2"
  model: "model"
  result: "result"
  base_path: 
  model_path: 
  explog_path: 
  mem_path: 
  result_path: 
  save_freq: 0.005
  save_freq_mints: 20
  print_freq: 5
  resume: True


ddp:
  local_rank: 
  use_ddp: 
  world_size: 


seed: 777
date: 2025_1004
workers: 8


debug: False


hydra:
  run:
    dir: outputs/my_experiment_name
